// This file is auto-generated by `ploy types`. Do not edit manually.

import type { D1Database } from "@meetploy/types";

declare module "@meetploy/nextjs" {
	interface PloyEnv {
		DB: D1Database;
	}
}

declare global {
	interface PloyEnv {
		DB: D1Database;
	}
}

export {};
